### ISSUE TITLE
F5 bigip - number of connections per member of a pool stays at 0

### ISSUE THREAD

**Issue by Tontonitch** [lausser/check_nwc_health#131]
check_nwc_health $Revision: 6.0.2.3 $ 
BIG-IP 11.5.1

On F5 bigip, while using the modes pool-connections or pool-complections, the number of connections per member of a pool stays at 0, while the number of connections for the pool itself is correct.

Checking the value via snmpwalk gives the correct value:
```
[root@monitorsrv1 custom_plugins]# snmpwalk -v 2c -c xxxxxx xxx.xxx.xxx.xxx 1.3.6.1.4.1.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80
SNMPv2-SMI::enterprises.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80 = Counter64: 15
[root@monitorsrv1 custom_plugins]#
```

But when debugging the check_nwc_health execution, I can see that the ltmPoolMemberStatServerCurConns stays to 0

```
[LTMPOOLMEMBER_20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80]
ltmNodeAddrStatusName: xxxxxxxxxxxxxxxxxx
ltmPoolMbrStatusAddr: xxx.xxx.xxx.xxx
ltmPoolMbrStatusAddrType: 1
ltmPoolMbrStatusAvailState: green
ltmPoolMbrStatusDetailReason: Pool member is available
ltmPoolMbrStatusEnabledState: enabled
ltmPoolMbrStatusNodeName: xxxxxxxxxxxxxxxx
ltmPoolMbrStatusParentType: 0
ltmPoolMbrStatusPoolName: xxxxxxxxxxxxxxx
ltmPoolMbrStatusPort: 80
ltmPoolMemberAddr: 192.168.45.81
ltmPoolMemberAddrType: 1
ltmPoolMemberAvailabilityState: 0
ltmPoolMemberConnLimit: 10000000
ltmPoolMemberDisabledParentType: 0
ltmPoolMemberDynamicRatio: 1
ltmPoolMemberEnabledState: 0
ltmPoolMemberMonitorRule: xxxxxxxxxxxxxx
ltmPoolMemberMonitorState: up
ltmPoolMemberMonitorStatus: up
ltmPoolMemberNewSessionEnable: 0
ltmPoolMemberNodeName: xxxxxxxxxxxx
ltmPoolMemberPoolName: xxxxxxxxxxxxxxxxx
ltmPoolMemberPort: 80
ltmPoolMemberPriority: 2
ltmPoolMemberRatio: 1
ltmPoolMemberSessionStatus: 1
ltmPoolMemberStatServerCurConns: 0
ltmPoolMemberStatServerPctConns: 0
ltmPoolMemberStatusReason:
ltmPoolMemberWeight: 0
ltmPoolMonitorRule: xxxxxxxxxxxxx
info: member xxxxxxxxxxxxxx has 0 connections (from max 10M)
```

BR,
Yannick

**Comment by Tontonitch** [comment]
More info:

I've added a debug line ("print" below)
```
  34416       $self->add_message(defined $self->opts->mitigation() ? $self->opts->mitigation() : CRITICAL);
  34417     }
  34418     if ($self->check_messages() || $self->mode  =~ /device::lb::pool::co.*tions/) {
  34419       foreach my $member (@{$self->{members}}) {
  34420 print Data::Dumper::Dumper(\$member);
  34421         $member->check();
  34422       }
  34423     }
  34424     $self->add_perfdata(
```
and grep what is important and hereunder the result. As you can see, ltmPoolMemberStatServerCurConns are 0

```
[root@monitorsrv1 ~]# /usr/lib64/nagios/custom_plugins/check_nwc_health_v3 '--community' 'xxxx' '--hostname' 'xxx' '--mode' 'pool-complections' --name /webmail/pool_inotes | egrep "bless|ltmPoolMemberPoolName|ltmPoolMemberNodeName|flat_indices|ltmPoolMemberStatServerCurConns"
$VAR1 = \bless( {
                   'ltmPoolMemberPoolName' => '/webmail/pool_inotes',
                   'flat_indices' => '20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.19.47.67.111.109.109.111.110.47.77.97.105.108.52.45.72.97.114.100.121.80',
                   'ltmPoolMemberNodeName' => '/Common/aaaaa',
                   'ltmPoolMemberStatServerCurConns' => 0,
$VAR1 = \bless( {
                   'ltmPoolMemberPoolName' => '/webmail/pool_inotes',
                   'flat_indices' => '20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80',
                   'ltmPoolMemberNodeName' => '/Common/bbbbb',
                   'ltmPoolMemberStatServerCurConns' => 0,
[root@monitorsrv1 ~]#
```


Doing the corresponding snmpwalks reports some connections (on one node not, but it's because I do this test during the night :-/)

```
[root@monitorsrv1 ~]#  snmpwalk -v 2c -c xxxx xxx 1.3.6.1.4.1.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.19.47.67.111.109.109.111.110.47.77.97.105.108.52.45.72.97.114.100.121.80
SNMPv2-SMI::enterprises.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.19.47.67.111.109.109.111.110.47.77.97.105.108.52.45.72.97.114.100.121.80 = Counter64: 0
[root@monitorsrv1 ~]#
[root@monitorsrv1 ~]#  snmpwalk -v 2c -c xxxx xxx 1.3.6.1.4.1.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80
SNMPv2-SMI::enterprises.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80 = Counter64: 8
[root@monitorsrv1 ~]#
```

**Comment by Tontonitch** [comment]
Are there some other info that could be useful for troubleshooting?
BR,
Yannick

**Comment by lausser** [comment]
Hi Yannick,



can you mail me the resulting file from

check_nwc_health …. --mode walk | bash



Gerhard



Von: Yannick Charton [mailto:notifications@github.com]
Gesendet: Samstag, 8. April 2017 23:39
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [lausser/check_nwc_health] F5 bigip - number of connections per 
member of a pool stays at 0 (#131)



More info:

I've added a debug line ("print" below)

  34416       $self->add_message(defined $self->opts->mitigation() ? 
$self->opts->mitigation() : CRITICAL);
  34417     }
  34418     if ($self->check_messages() || $self->mode  =~ 
/device::lb::pool::co.*tions/) {
  34419       foreach my $member (@{$self->{members}}) {
  34420 print Data::Dumper::Dumper(\$member);
  34421         $member->check();
  34422       }
  34423     }
  34424     $self->add_perfdata(

and grep what is important and hereunder the result. As you can see, 
ltmPoolMemberStatServerCurConns are 0

[root@monitorsrv1 ~]# /usr/lib64/nagios/custom_plugins/check_nwc_health_v3 
'--community' 'xxxx' '--hostname' 'xxx' '--mode' 'pool-complections' --name 
/webmail/pool_inotes | egrep 
"bless|ltmPoolMemberPoolName|ltmPoolMemberNodeName|flat_indices|ltmPoolMemberStatServerCurConns"
$VAR1 = \bless( {
                   'ltmPoolMemberPoolName' => '/webmail/pool_inotes',
                   'flat_indices' => 
'20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.19.47.67.111.109.109.111.110.47.77.97.105.108.52.45.72.97.114.100.121.80',
                   'ltmPoolMemberNodeName' => '/Common/aaaaa',
                   'ltmPoolMemberStatServerCurConns' => 0,
$VAR1 = \bless( {
                   'ltmPoolMemberPoolName' => '/webmail/pool_inotes',
                   'flat_indices' => 
'20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80',
                   'ltmPoolMemberNodeName' => '/Common/bbbbb',
                   'ltmPoolMemberStatServerCurConns' => 0,
[root@monitorsrv1 ~]#

Doing the corresponding snmpwalks reports some connections (on one node not, 
but it's because I do this test during the night :-/)

[root@monitorsrv1 ~]#  snmpwalk -v 2c -c xxxx xxx 
1.3.6.1.4.1.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.19.47.67.111.109.109.111.110.47.77.97.105.108.52.45.72.97.114.100.121.80
SNMPv2-SMI::enterprises.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.19.47.67.111.109.109.111.110.47.77.97.105.108.52.45.72.97.114.100.121.80 
= Counter64: 0
[root@monitorsrv1 ~]#
[root@monitorsrv1 ~]#  snmpwalk -v 2c -c xxxx xxx 
1.3.6.1.4.1.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80
SNMPv2-SMI::enterprises.3375.2.2.5.4.3.1.11.20.47.119.101.98.109.97.105.108.47.112.111.111.108.95.105.110.111.116.101.115.20.47.67.111.109.109.111.110.47.77.97.105.108.51.45.76.97.117.114.101.108.80 
= Counter64: 8
[root@monitorsrv1 ~]#

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/131#issuecomment-292747538> 
, or mute the thread

**Comment by Tontonitch** [comment]
Hello Gerhard,
Thanks for taking some time to look at my issue.
I just sent you by email the requested info + some extra stuff. Hope that it will help you in your investigations.
BR,
Yannick

**Comment by Tontonitch** [comment]
Hello Gerhard,
I updated the plugin to the lastest release 6.3.0.2, which includes your fix.
Number of connections per member of a pool are now correct.
Thanks for the fix.
BR,
Yannick
