### ISSUE TITLE
multiplication error Interface-health

### ISSUE THREAD

**Issue by stringbeansth** [lausser/check_nwc_health#135]
When using the interface-health mode some interfaces return without issue, but some interfaces including 10Gigabit & Port-Channels return with:

**Cisco Nexus 7k**
[root@ libexec]# ./check_nwc_health --hostname  --community  --mode interface-health --name Ethernet1/3
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 34501.
Mode interface-health is not implemented for this type of device

[root@ libexec]# ./check_nwc_health --hostname  --community  --mode interface-health --name Ethernet1/24
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 34501.
Mode interface-health is not implemented for this type of device

[root@ libexec]# ./check_nwc_health --hostname  --community  --mode interface-health --name Port-channel10
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 34501.
Mode interface-health is not implemented for this type of device

**Cisco 3850**
[root@ libexec]# ./check_nwc_health --hostname  --community  --mode interface-health --name TenGigabitEthernet1/1/3
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 34501.
Mode interface-health is not implemented for this type of device

Seems to be a common issue. Let me know if you need any further information.

Thanks!
Jason

**Comment by lausser** [comment]
Hi, can you please run check_nwc_health …. –mode snmpwalk  | bash and mail me the resulting files at  <mailto:gerhard.lausser@consol.de> gerhard.lausser@consol.de ? Gerhard Gesendet von  <https://go.microsoft.com/fwlink/?LinkId=550986> Mail für Windows 10 Von:  <mailto:notifications@github.com> stringbeansth
 Gesendet:  Dienstag, 2. Mai 2017 18:04
 An:  <mailto:check_nwc_health@noreply.github.com> lausser/check_nwc_health
 Cc:  <mailto:subscribed@noreply.github.com> Subscribed
 Betreff:  [lausser/check_nwc_health] multiplication error Interface-health (#135)When using the interface-health mode some interfaces return without issue, but some interfaces including 10Gigabit & Port-Channels return with:

**Cisco Nexus 7k**
[root@ libexec]# ./check_nwc_health --hostname  --community  --mode interface-health --name Ethernet1/3
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 34501.
Mode interface-health is not implemented for this type of device

[root@ libexec]# ./check_nwc_health --hostname  --community  --mode interface-health --name Ethernet1/24
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 34501.
Mode interface-health is not implemented for this type of device

[root@ libexec]# ./check_nwc_health --hostname  --community  --mode interface-health --name Port-channel10
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 34501.
Mode interface-health is not implemented for this type of device

**Cisco 3850**
[root@ libexec]# ./check_nwc_health --hostname  --community  --mode interface-health --name TenGigabitEthernet1/1/3
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 34501.
Mode interface-health is not implemented for this type of device

Seems to be a common issue. Let me know if you need any further information.

Thanks!
Jason




-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/lausser/check_nwc_health/issues/135

**Comment by stringbeansth** [comment]
file sent

**Comment by lausser** [comment]
Found the bug and pushed an update. Thanks!
btw, do NOT run check_nwc_health as root. Especially for the interface-modes it writes a temporary file in /var/tmp/check_nwc_health, which cannot be overwritten by the nagios user later.
