### ISSUE TITLE
LCOSMIB.pm s missing from GLPlungin

### ISSUE THREAD

**Issue by Mikesch-mp** [lausser/check_nwc_health#141]
Cant build module anymore because of missing file. Only if i delete the line in "plugin-scripts/Makefile.am" and run autoreconf & configure again.
````
[root@koelin01 check_nwc_health]# make
Making all in plugins-scripts
make[1]: Entering directory `/usr/local/src/check_nwc_health/plugins-scripts'
make[1]: *** No rule to make target `../GLPlugin/lib/Monitoring/GLPlugin/SNMP/MibsAndOids/LCOSMIB.pm', needed by `check_nwc_health'.  Stop.
make[1]: Leaving directory `/usr/local/src/check_nwc_health/plugins-scripts'
make: *** [all-recursive] Error 1
````

**Comment by lausser** [comment]
Should be ok now



Von: Carsten [mailto:notifications@github.com]
Gesendet: Dienstag, 20. Juni 2017 11:38
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [lausser/check_nwc_health] LCOSMIB.pm s missing from GLPlungin 
(#141)



Cant build module anymore because of missing file. Only if i delete the line 
in "plugin-scripts/Makefile.am" and run autoreconf & configure again.

[root@koelin01 check_nwc_health]# make
Making all in plugins-scripts
make[1]: Entering directory 
`/usr/local/src/check_nwc_health/plugins-scripts'
make[1]: *** No rule to make target 
`../GLPlugin/lib/Monitoring/GLPlugin/SNMP/MibsAndOids/LCOSMIB.pm', needed by 
`check_nwc_health'.  Stop.
make[1]: Leaving directory `/usr/local/src/check_nwc_health/plugins-scripts'
make: *** [all-recursive] Error 1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/141> , or mute the 
thread

**Comment by Mikesch-mp** [comment]
Yes works perfect again :) Thank you
