### ISSUE TITLE
option to have interface-health without broadcast?

### ISSUE THREAD

**Issue by avik78** [lausser/check_nwc_health#151]
Hi,
we are using the great interface-health-mode, but for many ports connected to routers and/or LACP-links to Fortigate and many of them have huge broadcast percentage, which doesn't create any problems.

Since we want to not report on broadcast, but still want to check interface-status, interface-errors, interface-usage and interface-discards - we have to replace the 1 interface-health check with 4 separate checks. If it could be possible to have "--ignore-broadcast", that would be appreciated.

Thanks,
Ole

**Comment by lausser** [comment]
What you can do is to set a high threshold only for the broadcasts. Have a look at the perfdata.
With --warningx <perflabel>=threshold and --criticalx <perflabel>=threshold you can set individual thresholds for certain metrics. If there is a '.*' in the label, then the new threshold applies to all matching metrics.
Try --warningx '.*broadcast.*'=99 --criticalx '.*broadcast.'=99
I recommend this, because then you still see the performance graphs, but get not annoyed by notifications.

**Comment by avik78** [comment]
Fantastic solution, even better! Thanks a lot for pointing me in that direction.

**Comment by Napsty** [comment]
Thanks for that hint with warningx and criticalx @lausser . 
Just as an additional info, the following line contains some typos which don't match all int_broadcast_in and int_broadcast_out:

> Try --warningx '.broadcast.'=99 --criticalx '.*broadcast.'=99

Append this to your Icinga 2 command definition for check_nwc_health:

```
  vars.nwc_warningx = ".*broadcast.*=99"
  vars.nwc_criticalx = ".*broadcast.*=99"
```

Successfully tested.
