### ISSUE TITLE
cpu-load with negative values which triggers an alarm

### ISSUE THREAD

**Issue by Tontonitch** [lausser/check_nwc_health#154]
check_nwc_health version: 6.3.0.2

hello,
we had some soft alarms with cpu-load < 0 when checking F5 BIGIP nodes.

![image](https://user-images.githubusercontent.com/600025/32666141-d15c08de-c636-11e7-9a52-19ddee19f45f.png)

I would expect only positive values for the cpu-load.

Br,
Yannick

**Comment by lausser** [comment]
This means that there was a rollover of the cpu counter.  How Long did the error persist?

**Comment by Tontonitch** [comment]
The error doesn't persist more than 1 consecutive time. So I don't have HARD critical states but only SOFT states, which didn't trigger notifications.
However, it happens quite often. For example, last friday:
![image](https://user-images.githubusercontent.com/600025/32993399-b9a8535a-cd57-11e7-9b8a-dee3db5133ff.png)
According to the time of the occurences, I don't think that it comes from network admin operations.

**Comment by lausser** [comment]
The cpu usage is calculated from more than one OIDs' values, which might roll over at different times or nearly at the same time or somehow misbehave at all.
I added some wrapper around the cpu_usage which checks it if is a positive value between 0 and 100. If this is true, then it is considered to be valid and gets saved in the tmp dir which check_nwc_health creates for other tmp-values.
Now when the OIDs have values which result in a negative cpu_usage, it gets replaced by the saved value, which is the last valid value. This is done for 3 times in a row, if the result is then still negative, it is output and results in critical. (because then something is really broken and it would be wrong to use the fake valid value for a longer time)
