### ISSUE TITLE
"0 has 0 of 0 running sub-layer interfaces" after deleting a Port-Channel

### ISSUE THREAD

**Issue by MarcusCaepio** [lausser/check_nwc_health#176]
Hi Mr. Lausser,

we are using the stack availability check for all Port-Channels:
  nwc_health_mode = "interface-stack-availability"
  nwc_health_regexp = true
  nwc_health_name = "Port-channel*"

on one host, we had a Port-Channel with 0 sub-layers. The check noticed as expected:
CRITICAL - Port-channel16 has 0 of 0 running sub-layer interfaces [...]

So we deleted the Port-Channel. But instead of an OK state, we got the following for a couple of minutes:
CRITICAL - 0 has 0 of 0 running sub-layer interfaces [....]

What could be the reason for this?
Thanks in advanced

**Comment by lausser** [comment]
Hi,



i rewrote the portchannel part this week, because we had the situation, 
where sublayer interfaces failed and were then intentionally removed from 
the ifStackTable. This is normal behavior with Arista, leading to undetected 
errors.

Please run the attached plugin and look if is better now.



Gerhard



Von: MarcusCaepio [mailto:notifications@github.com]
Gesendet: Freitag, 24. August 2018 11:23
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [lausser/check_nwc_health] "0 has 0 of 0 running sub-layer 
interfaces" after deleting a Port-Channel (#176)



Hi Mr. Lausser,

we are using the stack availability check for all Port-Channels:
nwc_health_mode = "interface-stack-availability"
nwc_health_regexp = true
nwc_health_name = "Port-channel*"

on one host, we had a Port-Channel with 0 sub-layers. The check noticed as 
expected:
CRITICAL - Port-channel16 has 0 of 0 running sub-layer interfaces [...]

So we deleted the Port-Channel. But instead of an OK state, we got the 
following for a couple of minutes:
CRITICAL - 0 has 0 of 0 running sub-layer interfaces [....]

What could be the reason for this?
Thanks in advanced

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/176> , or mute the 
thread

**Comment by lausser** [comment]
[check_nwc_health.txt](https://github.com/lausser/check_nwc_health/files/2318579/check_nwc_health.txt)

**Comment by MarcusCaepio** [comment]
thanks a lot. I will try 👍

**Comment by MarcusCaepio** [comment]
Seems to be fixed :)
