### ISSUE TITLE
Compilation problem (v. 7.10.0.6)

### ISSUE THREAD

**Issue by PiK2K** [lausser/check_nwc_health#216]
Hi,
I notice following error during make ("sudo ./configure; make" on Ubuntu 16.04.6):
(...)
Making all in plugins-scripts
make[1]: Entering directory '/home/xxx/check_nwc_health-7.10.0.6/plugins-scripts'
make[1]: *** No rule to make target 'Classes/UPNP/AVM/FritzBox7390/Components/InterfaceSubsystem.pm', needed by 'check_nwc_health'.  Stop.
make[1]: Leaving directory '/home/xxx/check_nwc_health-7.10.0.6/plugins-scripts'
Makefile:341: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by lausser** [comment]
Works perfectly here. I guess it’s a problem with your tar. Som eolder 
versions of tar do not extract files if the full path name is longer than 
100 characters. Unpack the tar.gz on another computer.



Von: PiK2K [mailto:notifications@github.com]
Gesendet: Freitag, 13. September 2019 19:32
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [lausser/check_nwc_health] Compilation problem (v. 7.10.0.6) (#216)



Hi,
I notice following error during make ("sudo ./configure; make" on Ubuntu 
16.04.6):
(...)
Making all in plugins-scripts
make[1]: Entering directory 
'/home/xxx/check_nwc_health-7.10.0.6/plugins-scripts'
make[1]: *** No rule to make target 
'Classes/UPNP/AVM/FritzBox7390/Components/InterfaceSubsystem.pm', needed by 
'check_nwc_health'. Stop.
make[1]: Leaving directory 
'/home/xxx/check_nwc_health-7.10.0.6/plugins-scripts'
Makefile:341: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/216?email_source=notifications&email_token=AABQSOE4ISJFLGQ2BZUV4W3QJPFAPA5CNFSM4IWSMGE2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HLJJCSA> 
, or mute the thread

**Comment by PiK2K** [comment]
You're absolutely right - thank you for such a quick response.
I did unpack via MC before (by copying the content), now I used command (tar xvfz ...) and everything compiled perfectly well.
Thanks again.

> Works perfectly here. I guess it’s a problem with your tar. Som eolder versions of tar do not extract files if the full path name is longer than 100 characters. Unpack the tar.gz on another computer.
