### ISSUE TITLE
After upgrade Cisco WLC HA status check OID changed

### ISSUE THREAD

**Issue by elguapo159** [lausser/check_nwc_health#247]
After upgrading a Cisco WLC HA setup from 8.5.135.0 to version 8.10.121.0, the current OID set (1.3.6.1.4.1.9.9.198888) is no longer implemented causing the HA status check to fail with "CRITICAL - ha failover is not configured". Cisco TAC points us to the MIB in attachment with OID 1.3.6.1.4.1.9.9.843 as the implemented OID for this new version.

Running an SNMPwalk using the new base oid returns the following:
CISCO-LWAPP-HA-MIB::cLHaApSsoConfig.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaPeerIpAddressType.0 = INTEGER: ipv4(1)
CISCO-LWAPP-HA-MIB::cLHaPeerIpAddress.0 = Hex-STRING: 0A 36 E3 51
CISCO-LWAPP-HA-MIB::cLHaServicePortPeerIpAddressType.0 = INTEGER: ipv4(1)
CISCO-LWAPP-HA-MIB::cLHaServicePortPeerIpAddress.0 = Hex-STRING: 0A 36 CD 73
CISCO-LWAPP-HA-MIB::cLHaServicePortPeerIpNetMaskType.0 = INTEGER: ipv4(1)
CISCO-LWAPP-HA-MIB::cLHaServicePortPeerIpNetMask.0 = Hex-STRING: FF FF FF 80
CISCO-LWAPP-HA-MIB::cLHaRedundancyIpAddressType.0 = INTEGER: ipv4(1)
CISCO-LWAPP-HA-MIB::cLHaRedundancyIpAddress.0 = Hex-STRING: A9 FE E3 51
CISCO-LWAPP-HA-MIB::cLHaPeerMacAddress.0 = STRING: a0:23:9f:fc:1f:4d
CISCO-LWAPP-HA-MIB::cLHaVirtualMacAddress.0 = STRING: a0:23:9f:8e:46:53
CISCO-LWAPP-HA-MIB::cLHaPrimaryUnit.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaLinkEncryption.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaNetworkFailOver.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaKATimeout.0 = Gauge32: 100 milliseconds
CISCO-LWAPP-HA-MIB::cLHaKARetryCount.0 = Gauge32: 6
CISCO-LWAPP-HA-MIB::cLHaGwRetryCount.0 = Gauge32: 12
CISCO-LWAPP-HA-MIB::cLHaPeerSearchTimeout.0 = Gauge32: 120 seconds
CISCO-LWAPP-HA-MIB::cLHaAllCpuUsage.0 = STRING: 0%/1%, 0%/0%, 0%/0%, 0%/0%, 0%/1%, 0%/1%
CISCO-LWAPP-HA-MIB::cLHaPowerSupply1Present.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaPowerSupply1Operational.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaPowerSupply2Present.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaPowerSupply2Operational.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaTotalSystemMemory.0 = INTEGER: 32381132 KBytes
CISCO-LWAPP-HA-MIB::cLHaFreeSystemMemory.0 = INTEGER: 28938104 KBytes
CISCO-LWAPP-HA-MIB::cLHaUsedSystemMemory.0 = INTEGER: 3443028 KBytes
CISCO-LWAPP-HA-MIB::cLHaAllocatedFromRtos.0 = INTEGER: 910687 KBytes
CISCO-LWAPP-HA-MIB::cLHaChunksFree.0 = INTEGER: 91
CISCO-LWAPP-HA-MIB::cLHaMmappedRegions.0 = INTEGER: 29
CISCO-LWAPP-HA-MIB::cLHaSpaceInMmappedRegions.0 = INTEGER: 1070780 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalAllocatedSpace.0 = INTEGER: 804248 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalNotInUseSpace.0 = INTEGER: 106438 KBytes
CISCO-LWAPP-HA-MIB::cLHaTopMostReleasableSpace.0 = INTEGER: 130 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalAllocatedInclMmap.0 = INTEGER: 1981467 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalUsedMmap.0 = INTEGER: 1875028 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalFreeInclMmap.0 = INTEGER: 106438 KBytes
CISCO-LWAPP-HA-MIB::cLHaAvgPeerReachLatency.0 = INTEGER: 237 Microseconds
CISCO-LWAPP-HA-MIB::cLHaAvgGwReachLatency.0 = INTEGER: 12525 Microseconds
CISCO-LWAPP-HA-MIB::cLHaBulkSyncStatus.0 = STRING: Complete

It looks like $Monitoring::GLPlugin::SNMP::MibsAndOids::mibs_and_oids->{'CISCO-LWAPP-HA-MIB'}  is differently and not completely implemented by Cisco in this version. Can this be investigated and updated?

[CISCO-LWAPP-HA-MIB.txt](https://github.com/lausser/check_nwc_health/files/4627504/CISCO-LWAPP-HA-MIB.txt)

Kind Regards

**Comment by lausser** [comment]
Can you please run

snmpwalk -ObentU ….. 1.3.6.1.2.1 > wlcha.txt

snmpwalk -ObentU ….. 1.3.6.1.4.1 >> wlcha.txt

and mail it to gerhard.lausser@consol.de <mailto:gerhard.lausser@consol.de>

I can’t promise to fix it and it may take a long time, but I’ll try.



Von: Van Hemelrijck [mailto:notifications@github.com]
Gesendet: Donnerstag, 14. Mai 2020 12:22
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [lausser/check_nwc_health] After upgrade Cisco WLC HA status check 
OID changed (#247)



After upgrading a Cisco WLC HA setup from 8.5.135.0 to version 8.10.121.0, 
the current OID set (1.3.6.1.4.1.9.9.198888) is no longer implemented 
causing the HA status check to fail with "CRITICAL - ha failover is not 
configured". Cisco TAC points us to the MIB in attachment with OID 
1.3.6.1.4.1.9.9.843 as the implemented OID for this new version.

Running an SNMPwalk using the new base oid returns the following:
CISCO-LWAPP-HA-MIB::cLHaApSsoConfig.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaPeerIpAddressType.0 = INTEGER: ipv4(1)
CISCO-LWAPP-HA-MIB::cLHaPeerIpAddress.0 = Hex-STRING: 0A 36 E3 51
CISCO-LWAPP-HA-MIB::cLHaServicePortPeerIpAddressType.0 = INTEGER: ipv4(1)
CISCO-LWAPP-HA-MIB::cLHaServicePortPeerIpAddress.0 = Hex-STRING: 0A 36 CD 73
CISCO-LWAPP-HA-MIB::cLHaServicePortPeerIpNetMaskType.0 = INTEGER: ipv4(1)
CISCO-LWAPP-HA-MIB::cLHaServicePortPeerIpNetMask.0 = Hex-STRING: FF FF FF 80
CISCO-LWAPP-HA-MIB::cLHaRedundancyIpAddressType.0 = INTEGER: ipv4(1)
CISCO-LWAPP-HA-MIB::cLHaRedundancyIpAddress.0 = Hex-STRING: A9 FE E3 51
CISCO-LWAPP-HA-MIB::cLHaPeerMacAddress.0 = STRING: a0:23:9f:fc:1f:4d
CISCO-LWAPP-HA-MIB::cLHaVirtualMacAddress.0 = STRING: a0:23:9f:8e:46:53
CISCO-LWAPP-HA-MIB::cLHaPrimaryUnit.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaLinkEncryption.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaNetworkFailOver.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaKATimeout.0 = Gauge32: 100 milliseconds
CISCO-LWAPP-HA-MIB::cLHaKARetryCount.0 = Gauge32: 6
CISCO-LWAPP-HA-MIB::cLHaGwRetryCount.0 = Gauge32: 12
CISCO-LWAPP-HA-MIB::cLHaPeerSearchTimeout.0 = Gauge32: 120 seconds
CISCO-LWAPP-HA-MIB::cLHaAllCpuUsage.0 = STRING: 0%/1%, 0%/0%, 0%/0%, 0%/0%, 
0%/1%, 0%/1%
CISCO-LWAPP-HA-MIB::cLHaPowerSupply1Present.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaPowerSupply1Operational.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaPowerSupply2Present.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaPowerSupply2Operational.0 = INTEGER: true(1)
CISCO-LWAPP-HA-MIB::cLHaTotalSystemMemory.0 = INTEGER: 32381132 KBytes
CISCO-LWAPP-HA-MIB::cLHaFreeSystemMemory.0 = INTEGER: 28938104 KBytes
CISCO-LWAPP-HA-MIB::cLHaUsedSystemMemory.0 = INTEGER: 3443028 KBytes
CISCO-LWAPP-HA-MIB::cLHaAllocatedFromRtos.0 = INTEGER: 910687 KBytes
CISCO-LWAPP-HA-MIB::cLHaChunksFree.0 = INTEGER: 91
CISCO-LWAPP-HA-MIB::cLHaMmappedRegions.0 = INTEGER: 29
CISCO-LWAPP-HA-MIB::cLHaSpaceInMmappedRegions.0 = INTEGER: 1070780 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalAllocatedSpace.0 = INTEGER: 804248 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalNotInUseSpace.0 = INTEGER: 106438 KBytes
CISCO-LWAPP-HA-MIB::cLHaTopMostReleasableSpace.0 = INTEGER: 130 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalAllocatedInclMmap.0 = INTEGER: 1981467 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalUsedMmap.0 = INTEGER: 1875028 KBytes
CISCO-LWAPP-HA-MIB::cLHaTotalFreeInclMmap.0 = INTEGER: 106438 KBytes
CISCO-LWAPP-HA-MIB::cLHaAvgPeerReachLatency.0 = INTEGER: 237 Microseconds
CISCO-LWAPP-HA-MIB::cLHaAvgGwReachLatency.0 = INTEGER: 12525 Microseconds
CISCO-LWAPP-HA-MIB::cLHaBulkSyncStatus.0 = STRING: Complete

It looks like 
$Monitoring::GLPlugin::SNMP::MibsAndOids::mibs_and_oids->{'CISCO-LWAPP-HA-MIB'} 
is differently and not completely implemented by Cisco in this version. Can 
this be investigated and updated?

CISCO-LWAPP-HA-MIB.txt 
<https://github.com/lausser/check_nwc_health/files/4627504/CISCO-LWAPP-HA-MIB.txt>

Kind Regards

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/247> , or unsubscribe

**Comment by elguapo159** [comment]
I have sent you the output as requested!

**Comment by lausser** [comment]
Yes, got it



Von: Van Hemelrijck [mailto:notifications@github.com]
Gesendet: Donnerstag, 14. Mai 2020 15:07
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Gerhard Lausser <Gerhard.Lausser@consol.de>; Comment 
<comment@noreply.github.com>
Betreff: Re: [lausser/check_nwc_health] After upgrade Cisco WLC HA status 
check OID changed (#247)



I have sent you the output as requested!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/247#issuecomment-628622293> 
, or unsubscribe
