### ISSUE TITLE
autoconf not working

### ISSUE THREAD

**Issue by varac** [lausser/check_nwc_health#42]
i can't get autoconf/the resulting configure script working:

```
--- monitoring/check_nwc_health ‹master› » autoconf
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:6: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:58: error: possibly undefined macro: AM_CONDITIONAL
--- monitoring/check_nwc_health ‹master* ⁇› » ./configure
./configure: line 1713: syntax error near unexpected token `1.9'
./configure: line 1713: `AM_INIT_AUTOMAKE(1.9 tar-pax)'

--- monitoring/check_nwc_health ‹master* ⁇› » autoconf --version
autoconf (GNU Autoconf) 2.69
…
```

btw, please update the README.md to include that autoconf is needed!

**Comment by k0ste** [comment]
Same.

```
[k0ste@WorkStation tmp]$ git clone https://github.com/lausser/check_nwc_health.git
Cloning into 'check_nwc_health'...
remote: Counting objects: 6839, done.
remote: Total 6839 (delta 0), reused 0 (delta 0), pack-reused 6839
Receiving objects: 100% (6839/6839), 8.47 MiB | 1.84 MiB/s, done.
Resolving deltas: 100% (4276/4276), done.
Checking connectivity... done.
[k0ste@WorkStation tmp]$ 
[k0ste@WorkStation check_nwc_health]$ autoconf 
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:6: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:58: error: possibly undefined macro: AM_CONDITIONAL
[k0ste@WorkStation check_nwc_health]$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
[k0ste@WorkStation check_nwc_health]$ 
```

**Comment by lausser** [comment]
can you try autoreconf instead of autoconf?



Von: Konstantin Shalygin [mailto:notifications@github.com]
Gesendet: Donnerstag, 4. Februar 2016 12:04
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Betreff: Re: [check_nwc_health] autoconf not working (#42)



Same.

[k0ste@WorkStation tmp]$ git clone 
https://github.com/lausser/check_nwc_health.git
Cloning into 'check_nwc_health'...
remote: Counting objects: 6839, done.
remote: Total 6839 (delta 0), reused 0 (delta 0), pack-reused 6839
Receiving objects: 100% (6839/6839), 8.47 MiB | 1.84 MiB/s, done.
Resolving deltas: 100% (4276/4276), done.
Checking connectivity... done.
[k0ste@WorkStation tmp]$
[k0ste@WorkStation check_nwc_health]$ autoconf
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:6: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:58: error: possibly undefined macro: AM_CONDITIONAL
[k0ste@WorkStation check_nwc_health]$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, 
<http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
[k0ste@WorkStation check_nwc_health]$

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/42#issuecomment-179772599> 
.

**Comment by k0ste** [comment]
Works, but make failed:

```
[k0ste@WorkStation check_nwc_health]$ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
[k0ste@WorkStation check_nwc_health]$ autoreconf 
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.
Makefile.am:4: warning: shell which dos2unix || which fromdos: non-POSIX variable name
Makefile.am:4: (probably a GNU make extension)
[k0ste@WorkStation check_nwc_health]$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether make sets $(MAKE)... (cached) yes
checking for gawk... (cached) gawk
checking for sh... /usr/bin/sh
checking for perl... /usr/bin/perl
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating plugins-scripts/Makefile
config.status: creating plugins-scripts/subst
                       --with-perl: /usr/bin/perl
                --with-nagios-user: nagios
               --with-nagios-group: nagios
              --disable-standalone: 
[k0ste@WorkStation check_nwc_health]$ make
Making all in plugins-scripts
make[1]: Entering directory '/tmp/check_nwc_health/plugins-scripts'
make[1]: *** No rule to make target '../lib/Monitoring/GLPlugin/Commandline/Getopt.pm', needed by 'check_nwc_health'.  Stop.
make[1]: Leaving directory '/tmp/check_nwc_health/plugins-scripts'
Makefile:340: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by lausser** [comment]
i forgot...

to build check_nwc_health from the git repo, you also need 
https://github.com/lausser/GLPlugin

Both repositories have to be side by side in a common subdirectory, so that 
in the  check_nwc_health-subdirectory you can see a ../GLPlugin

Then, initially make a

cd check_nwc_health; cp -r ../GLPlugin/lib .

Then you have everything to make.



Gerhard



Von: Konstantin Shalygin [mailto:notifications@github.com]
Gesendet: Donnerstag, 4. Februar 2016 13:39
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Gerhard Lausser <Gerhard.Lausser@consol.de>
Betreff: Re: [check_nwc_health] autoconf not working (#42)



Works, but make failed:

[k0ste@WorkStation check_nwc_health]$ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, 
<http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
[k0ste@WorkStation check_nwc_health]$ autoreconf
Unescaped left brace in regex is deprecated, passed through in regex; marked 
by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 
3936.
Makefile.am:4: warning: shell which dos2unix || which fromdos: non-POSIX 
variable name
Makefile.am:4: (probably a GNU make extension)
[k0ste@WorkStation check_nwc_health]$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether make sets $(MAKE)... (cached) yes
checking for gawk... (cached) gawk
checking for sh... /usr/bin/sh
checking for perl... /usr/bin/perl
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating plugins-scripts/Makefile
config.status: creating plugins-scripts/subst
                       --with-perl: /usr/bin/perl
                --with-nagios-user: nagios
               --with-nagios-group: nagios
              --disable-standalone:
[k0ste@WorkStation check_nwc_health]$ make
Making all in plugins-scripts
make[1]: Entering directory '/tmp/check_nwc_health/plugins-scripts'
make[1]: *** No rule to make target 
'../lib/Monitoring/GLPlugin/Commandline/Getopt.pm', needed by 
'check_nwc_health'.  Stop.
make[1]: Leaving directory '/tmp/check_nwc_health/plugins-scripts'
Makefile:340: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/42#issuecomment-179809484> 
.

**Comment by k0ste** [comment]
Yes, it works. Best way to do it (git it git) - submodule.
I can make PR with it and readme. If need...

**Comment by zijam** [comment]
that would be great :+1:

**Comment by k0ste** [comment]
https://github.com/lausser/check_nwc_health/pull/58

Need to fix makefiles about 'lib' path. 'lib' -> 'GLPlugin/lib'. Or just create symlink...
