### ISSUE TITLE
Checkpoint VSX connections wrong

### ISSUE THREAD

**Issue by Napsty** [lausser/check_nwc_health#57]
When Checkpoint is not a FW-1 but a VSX, the "fw-connections" check is wrong. fw-connections checks for the number of connections in the following oid:

     'fwNumConn' => '1.3.6.1.4.1.2620.1.1.25.3.0',

However in Checkpoint VSX, the correct OID to retrieve the current number of connections is the following: 1.3.6.1.4.1.2620.1.16.23.1.1.2

Furthermore, this OID can return multiple values (per virtual system id):

    # snmpwalk -v 2c -c monitoring vxsip 1.3.6.1.4.1.2620.1.16.23.1.1.2
    iso.3.6.1.4.1.2620.1.16.23.1.1.2.1.0 = Counter32: 58
    iso.3.6.1.4.1.2620.1.16.23.1.1.2.2.0 = Counter32: 0
    iso.3.6.1.4.1.2620.1.16.23.1.1.2.3.0 = Counter32: 6077
    iso.3.6.1.4.1.2620.1.16.23.1.1.2.4.0 = Counter32: 0
    iso.3.6.1.4.1.2620.1.16.23.1.1.2.5.0 = Counter32: 10246

There are two changes that need to be done to the plugin:

1. Auto-detect that this is a VSX, not a classical FW-1 firewall (maybe check if OID 1.3.6.1.4.1.2620.1.16.23.1.1.2 returns something valid)

2. Get the values of all found entries of the OID 1.3.6.1.4.1.2620.1.16.23.1.1.2 and make a sum for the real number of fw-connections.

All other checks seem to work fine (tested with hardware-health, interface-usage, uptime, cpu-load, memory-usage, ha-role, svn-status.

**Comment by Napsty** [comment]
Hello Gerhard,

So far I came to the following "solution" by modifying the init subroutine of "Classes::CheckPoint::Firewall1::Component::FwSubsystem". 

    package Classes::CheckPoint::Firewall1::Component::FwSubsystem;
    our @ISA = qw(Monitoring::GLPlugin::SNMP::Item);
    use strict;
    
    sub init {
      my $self = shift;
      $self->get_snmp_objects('CHECKPOINT-MIB', (qw(vsxVsInstalled)));
      # Check whether this Checkpoint system is a virtual VSX system (different OIDs for connections)
      if ($self->{vsxVsInstalled}) {
        $self->add_info(sprintf 'Detected a CheckPoint VSX system');
        $self->get_snmp_objects('CHECKPOINT-MIB', (qw(
            fwModuleState fwPolicyName)));
        my $fwNumConn = 0;
        my @connections = `snmpwalk -v 2c -c public -O vqe vsxip 1.3.6.1.4.1.2620.1.16.23.1.1.2`;
        foreach (@connections) { 
          $self->add_info(sprintf 'Found %d connections', $_);
          $fwNumConn += $_; 
        }
        $self->add_info(sprintf 'Total combined connections: %d', $fwNumConn);
        $self->{fwNumConn} = $fwNumConn;
      } else {
        $self->get_snmp_objects('CHECKPOINT-MIB', (qw(
            fwModuleState fwPolicyName fwNumConn)));
        my $fwNumConn = $self->{fwNumConn};
      }
      if ($self->mode =~ /device::fw::policy::installed/) {
      } elsif ($self->mode =~ /device::fw::policy::connections/) {
      }
      
    }

The following OID's were added into CHECKPOINT-MIB definition:

    'vsxVsInstalled' => '1.3.6.1.4.1.2620.1.16.13.0',
    'VsxNumConn' => '1.3.6.1.4.1.2620.1.16.23.1.1.2',
    'VsxPeakNumConn' => '1.3.6.1.4.1.2620.1.16.23.1.1.3',

This works:

    # ./check_nwc_health.cktest --hostname vsxip --community public --mode fw-connections -v -v -v 
    I am a Linux fw-entp001 2.6.18-92cpx86_64 #1 SMP Tue Dec 1 00:35:54 IST 2015 x86_64
    [FWSUBSYSTEM]
    fwModuleState: Installed
    fwNumConn: 12621
    fwPolicyName: fw-vsx-01_VSX
    vsxVsInstalled: 2
    info: checking fw module
    
    OK - policy fw-vsx-01_VSX has 12621 open connections
    Detected a CheckPoint VSX system
    Found 57 connections
    Found 0 connections
    Found 5344 connections
    Found 0 connections
    Found 7220 connections
    Total combined connections: 12621
    checking fw module | 'fw_policy_numconn'=12621;20000;23000;;`

But this is of course ugly with the hardcoded snmpwalk command. Unfortunately I couldnt get it to work with either get_snmp_objects or get_snmp_table_objects. The values seem to be stored in hashes instead of arrays and this is where my Perl knowledge ends. I also don't know how to reference the values to read them correctly. If you are able to replace the snmpwalk command with the correct functions, that would be greatly appreciated!

**Comment by lausser** [comment]
Hi,

i will implement your VSX, but it will take a few days.

Gerhard



Von: Claudio Kuenzler [mailto:notifications@github.com]
Gesendet: Donnerstag, 4. Februar 2016 13:19
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Betreff: Re: [check_nwc_health] Checkpoint VSX connections wrong (#57)



Hello Gerhard,

So far I came to the following "solution" by modifying the init subroutine 
of "Classes::CheckPoint::Firewall1::Component::FwSubsystem".

package Classes::CheckPoint::Firewall1::Component::FwSubsystem;
our @ISA = qw(Monitoring::GLPlugin::SNMP::Item);
use strict;

sub init {
  my $self = shift;
  $self->get_snmp_objects('CHECKPOINT-MIB', (qw(vsxVsInstalled)));
  # Check whether this Checkpoint system is a virtual VSX system (different 
OIDs for connections)
  if ($self->{vsxVsInstalled}) {
    $self->add_info(sprintf 'Detected a CheckPoint VSX system');
    $self->get_snmp_objects('CHECKPOINT-MIB', (qw(
        fwModuleState fwPolicyName)));
    my $fwNumConn = 0;
    my @connections = `snmpwalk -v 2c -c public -O vqe vsxip 
1.3.6.1.4.1.2620.1.16.23.1.1.2`;
    foreach (@connections) {
      $self->add_info(sprintf 'Found %d connections', $_);
      $fwNumConn += $_;
    }
    $self->add_info(sprintf 'Total combined connections: %d', $fwNumConn);
    $self->{fwNumConn} = $fwNumConn;
  } else {
    $self->get_snmp_objects('CHECKPOINT-MIB', (qw(
        fwModuleState fwPolicyName fwNumConn)));
    my $fwNumConn = $self->{fwNumConn};
  }
  if ($self->mode =~ /device::fw::policy::installed/) {
  } elsif ($self->mode =~ /device::fw::policy::connections/) {
  }

}

The following OID's were added into CHECKPOINT-MIB definition:

'vsxVsInstalled' => '1.3.6.1.4.1.2620.1.16.13.0',
'VsxNumConn' => '1.3.6.1.4.1.2620.1.16.23.1.1.2',
'VsxPeakNumConn' => '1.3.6.1.4.1.2620.1.16.23.1.1.3',

This works:

# ./check_nwc_health.cktest --hostname vsxip --community public --mode 
fw-connections -v -v -v
I am a Linux fw-entp001 2.6.18-92cpx86_64 #1 SMP Tue Dec 1 00:35:54 IST 2015 
x86_64
[FWSUBSYSTEM]
fwModuleState: Installed
fwNumConn: 12621
fwPolicyName: fw-vsx-01_VSX
vsxVsInstalled: 2
info: checking fw module

OK - policy fw-vsx-01_VSX has 12621 open connections
Detected a CheckPoint VSX system
Found 57 connections
Found 0 connections
Found 5344 connections
Found 0 connections
Found 7220 connections
Total combined connections: 12621
checking fw module | 'fw_policy_numconn'=12621;20000;23000;;`

But this is of course ugly with the hardcoded snmpwalk command. 
Unfortunately I couldnt get it to work with either get_snmp_objects or 
get_snmp_table_objects. The values seem to be stored in hashes instead of 
arrays and this is where my Perl knowledge ends. I also don't know how to 
reference the values to read them correctly. If you are able to replace the 
snmpwalk command with the correct functions, that would be greatly 
appreciated!

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/57#issuecomment-179797317> 
.

**Comment by Napsty** [comment]
Cool, thanks! :+1:

**Comment by lausser** [comment]
Can you please run ./check_nwc_health ..... --mode walk
you'll get two snmpwalk commands. Pipe them to a Shell and mail me (Gerhard.lausser@consol.de) the resulting output file. The connectios of the vsx are in a table, so i will walk through all of them and make performancedata like Connections_total=100 Connections_vsx1=80 Connections_vsx2=.....

**Comment by Napsty** [comment]
Seems to work since commit 1247f0665377ba9c0a4cfc9777e9336beb2da6a3. Thanks!
