### ISSUE TITLE
Pulse Secure Gateways not supported any more

### ISSUE THREAD

**Issue by crsprsp** [lausser/check_nwc_health#81]
Hello Gerhard, 

i've updated to V5.6 and my health check for the Pulse Secure Gateways (ex. Juniper SAGates) does not work any more. 
"Mode hardware-health is not implemented for this type of device"
The old(!) V3.2.0.1 i used before it worked perfectly.
Is it possible to make that working again?

greets, Rico

**Comment by lausser** [comment]
Hi,



can you please run

check_nwc_health ….. --mode walk

It will show you two commands. Run these too and mail me the resultung 
snmpwalk-file, please. (gerhard.lausser@consol.de 
<mailto:gerhard.lausser@consol.de> )



Gerhard



Von: crsprsp [mailto:notifications@github.com]
Gesendet: Dienstag, 10. Mai 2016 11:28
An: lausser/check_nwc_health
Betreff: [lausser/check_nwc_health] Pulse Secure Gateways not supported any 
more (#81)



Hello Gerhard,

i've updated to V5.6 and my health check for the Pulse Secure Gateways (ex. 
Juniper SAGates) does not work any more.
"Mode hardware-health is not implemented for this type of device"
The old(!) V3.2.0.1 i used before it worked perfectly.
Is it possible to make that working again?

greets, Rico

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/81>

**Comment by lausser** [comment]
make a git pull (also in the GLPlugin subdirectory), it should work now.
