### ISSUE TITLE
checkpoint hardware-health wrong status with --warningx and --criticalx

### ISSUE THREAD

**Issue by Benedikt1992** [lausser/check_nwc_health#82]
E.g. on a checkpoint I have /boot which has 24% sapce free

now the check `check_nwc_health --mode hardware-health --name xxx --comunity xxx --warrningx /boot_free_pct=20 --criticalx /boot_free_pct=10` should be OK since the sapce has more than 20% space left. But it is critical! 

It seems that the check works like 
actual value > critical/warning limit => Not OK but it should be 
actual value **<** critical/warning limit => Not OK

**Comment by lausser** [comment]
1)  --warrningx -> --warningx

2)  https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
The CRITICAL is correct here. --criticalx /boot_free_pct=10 means: critical, 
if _more_ than 10



Gerhard



Von: Benedikt Bock [mailto:notifications@github.com]
Gesendet: Donnerstag, 12. Mai 2016 12:00
An: lausser/check_nwc_health
Betreff: [lausser/check_nwc_health] checkpoint hardware-health wrong status 
with --warningx and --criticalx (#82)



E.g. on a checkpoint I have /boot which has 24% sapce free

now the check check_nwc_health --mode hardware-health --name xxx --comunity 
xxx --warrningx /boot_free_pct=20 --criticalx /boot_free_pct=10 should be OK 
since the sapce has more than 20% space left. But it is critical!

It seems that the check works like
actual value > critical/warning limit => Not OK but it should be
actual value < critical/warning limit => Not OK

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/82> 
<https://github.com/notifications/beacon/AAMJODWiwuAulWE_hQCHhtKWptRCDA9Tks5qAvobgaJpZM4Ic6Fv.gif>

**Comment by Benedikt1992** [comment]
Right. My fault.. Thank You
