### ISSUE TITLE
Dynamic time margin in config check

### ISSUE THREAD

**Issue by Napsty** [lausser/check_nwc_health#84]
Currently the time margin between running and saved config is hardcoded to 300s (5min) in plugins-scripts/Classes/Cisco/IOS/Component/ConfigSubsystem.pm: 

    sub check {
      my $self = shift;
      my $info;
      my $runningChangedMarginAfterReload = 300;
      $self->add_info('checking config');
    [...]
        # If running config is reported to have changed within the (5 minute) margin since the last reload
        if (($runningUnchangedDuration + $runningChangedMarginAfterReload) > $self->uptime()) {
          $self->add_ok(sprintf("running config has not changed since reload (using a %d second margin)",
              $runningChangedMarginAfterReload));

It would be nice if $runningChangedMarginAfterReload could be dynamically adjusted with a parameter.

**Comment by Napsty** [comment]
For our network team I hardcoded the $runningChangedMarginAfterReload to 86400 (1d). But the plugin still reports a CRITICAL:

	# /usr/lib/nagios/plugins/check_nwc_health --hostname myswitch --community public --mode check-config -v -v -v
	I am a Cisco IOS Software, C3750 Software (C3750-IPSERVICESK9-M), Version 12.2(44)SE, RELEASE SOFTWARE (fc1)
	Copyright (c) 1986-2008 by Cisco Systems, Inc.
	Compiled Sat 05-Jan-08 00:29 by weiliu
	[CONFIG]
	ccmHistoryRunningLastChanged: 1421205422.24 (Wed Jan 14 04:17:02 2015)
	ccmHistoryRunningLastSaved: 1421205467.58 (Wed Jan 14 04:17:47 2015)
	ccmHistoryStartupLastChanged: 1421204632.35 (Wed Jan 14 04:03:52 2015)
	CRITICAL - running config is ahead of startup config since 715857 minutes. changes will be lost in case of a reboot
	checking config
	running config is ahead of startup config since 715857 minutes. changes will be lost in case of a reboot

So with the margin of 1d (which is much higher than the ~14mins here) there shouldn't be any critical output anymore. Or do I misunderstand something?

**Comment by mhoogveld** [comment]
Hi Claudio,

I have done some research into this check and added the margin.
Correct me if I'm wrong, but this is what's happening.
After a config save, the startupLastChanged is set to the current time. On
every change in the running config (or even after just entering the config
with "conf t"), the runningLastChanged is set to the current time.
(runningLastSaved is ignored for this check) If the runningLastChanged-time
> startupLastChanged-time, the config is considered unsaved.

The reason for the existence of this 5 minute margin is because of some
quirk in IOS. Directly after the router reboots, the
runningLastChanged-time is set to a few seconds, and sometimes as much as 3
minutes, later than the startupLastChanged-time. While the running config
has not changed, this would still trigger this check.
This difference in times after a reload is what the
$runningChangedMarginAfterReload is used for. This also means that changes
made up to 5 min after a config save, will not be detected. Therefor
setting it to a day is not advisable.
Because the exact meaning of this (hard-coded) variable is quite hard to
understand or explain, I don't see it becoming a parameter.

In your example, the difference between runningLastChanged and
startupLastChanged is about 13 minutes which should trigger the
unsaved-config flag with the 5 minute margin but not with the margin of a
day you have set.
Just out of curiosity, is this the state the switch is in after only a
reboot and without anyone modifying the config (even with just "conf t")?


Groet,
Maarten

**Comment by Napsty** [comment]
Hi Maarten

Thx for the quick answer. The network admin has made some configuration adaptations, but the dates didn't change - at least not the timeticks retrieved by SNMP. These are old firmwares (2008) and who knows what bugs were fixed since then. 
Anyway, if I understood the network admin correctly, a firmware upgrade will not be done in the next few months (don't ask me why...) so to correctly use the check with the status quo, I though I'd simply increase the margin according to the network admin (quote: "In some scenarios, for example traffic sniffing, we don't save the configs so set it to one day"). I thought that would work, as 1d (86400 seconds) is much higher than the 13mins difference - yet the plugin still returns critical and I don't know why. 
So is this a bug in the plugin calculation?

**Comment by mhoogveld** [comment]
The right (and hopefully easiest) solution would be to just save the config on the switch.
However, if sometimes configs are not saved as mentioned in the quote, this check just does not work. If such a scenario happen today, you would need to set the margin to at least one year and 4 months (since jan-2015). This margin should only be used as a fix for the time-difference just after a reload and should be as short as possible.

In this current state the difference is "only" 13 minutes and setting the margin to one day should work. I don't know why it doesn't in your case (are you sure it's set to 1 day in the actual compiled script you're running?) You could find if it's a bug by adding some strategic print statements.

**Comment by lausser** [comment]
adding „-vvvvvvvvvvvvvv“ (i think it must be more than ten times v) will 
show the communitcation and some OIDs/Values. Maybe this helps before adding 
printf statements.





Von: mhoogveld [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. Mai 2016 10:07
An: lausser/check_nwc_health
Betreff: Re: [lausser/check_nwc_health] Dynamic time margin in config check 
(#84)



The right (and hopefully easiest) solution would be to just save the config 
on the switch.
However, if sometimes configs are not saved as mentioned in the quote, this 
check just does not work. If such a scenario happen today, you would need to 
set the margin to at least one year and 4 months (since jan-2015). This 
margin should only be used as a fix for the time-difference just after a 
reload and should be as short as possible.

In this current state the difference is "only" 13 minutes and setting the 
margin to one day should work. I don't know why it doesn't in your case (are 
you sure it's set to 1 day in the actual compiled script you're running?) 
You could find if it's a bug by adding some strategic print statements.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/84#issuecomment-221502182>

**Comment by Napsty** [comment]
Yes, I did that already and it gave me the following output:

	/usr/lib/nagios/plugins/check_nwc_health --hostname myswitch --community public --mode check-config -v -v -v -v -v -v -v -v -v -v -v -v -v -v -v -v
	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Device::check_messages

	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::MIB2MIB
	Wed May 25 08:09:02 2016: cache: 1.3.6.1.2.1.1.3.0
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::MIB2MIB
	Wed May 25 08:09:02 2016: GET: MIB-2-MIB::sysUpTime (1.3.6.1.2.1.1.3.0) : 213823316
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::SNMPFRAMEWORKMIB
	Wed May 25 08:09:02 2016: cache: 1.3.6.1.6.3.10.2.1.3.0
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::SNMPFRAMEWORKMIB
	Wed May 25 08:09:02 2016: GET: SNMP-FRAMEWORK-MIB::snmpEngineTime (1.3.6.1.6.3.10.2.1.3.0) : 45087710
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::MIB2MIB
	Wed May 25 08:09:02 2016: cache: 1.3.6.1.2.1.1.1.0
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::MIB2MIB
	Wed May 25 08:09:02 2016: GET: MIB-2-MIB::sysDescr (1.3.6.1.2.1.1.1.0) : Cisco IOS Software, C3750 Software (C3750-IPSERVICESK9-M), Version 12.2(44)SE, RELEASE SOFTWARE (fc1)
	Copyright (c) 1986-2008 by Cisco Systems, Inc.
	Compiled Sat 05-Jan-08 00:29 by weiliu
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::MIB2MIB
	Wed May 25 08:09:02 2016: cache: 1.3.6.1.2.1.1.2.0
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::MIB2MIB
	Wed May 25 08:09:02 2016: GET: MIB-2-MIB::sysObjectID (1.3.6.1.2.1.1.2.0) : 1.3.6.1.4.1.9.1.516
	Wed May 25 08:09:02 2016: uptime: 45087710
	Wed May 25 08:09:02 2016: up since: Sat Dec 20 10:47:12 2014
	Wed May 25 08:09:02 2016: whoami: Cisco IOS Software, C3750 Software (C3750-IPSERVICESK9-M), Version 12.2(44)SE, RELEASE SOFTWARE (fc1)
	Copyright (c) 1986-2008 by Cisco Systems, Inc.
	Compiled Sat 05-Jan-08 00:29 by weiliu
	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Device::check_messages

	I am a Cisco IOS Software, C3750 Software (C3750-IPSERVICESK9-M), Version 12.2(44)SE, RELEASE SOFTWARE (fc1)
	Copyright (c) 1986-2008 by Cisco Systems, Inc.
	Compiled Sat 05-Jan-08 00:29 by weiliu
	Wed May 25 08:09:02 2016: using Classes::Cisco
	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::override_opt

	Wed May 25 08:09:02 2016: AUTOLOAD Monitoring::GLPlugin::Commandline::override_opt

	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::check_messages

	Wed May 25 08:09:02 2016: using Classes::Cisco::IOS
	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::IOS::analyze_and_check_config_subsystem

	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::CISCOCONFIGMANMIB
	Wed May 25 08:09:02 2016: cache: 1.3.6.1.4.1.9.9.43.1.1.1.0
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::CISCOCONFIGMANMIB
	Wed May 25 08:09:02 2016: GET: CISCO-CONFIG-MAN-MIB::ccmHistoryRunningLastChanged (1.3.6.1.4.1.9.9.43.1.1.1.0) : 213658924
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::CISCOCONFIGMANMIB
	Wed May 25 08:09:02 2016: cache: 1.3.6.1.4.1.9.9.43.1.1.2.0
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::CISCOCONFIGMANMIB
	Wed May 25 08:09:02 2016: GET: CISCO-CONFIG-MAN-MIB::ccmHistoryRunningLastSaved (1.3.6.1.4.1.9.9.43.1.1.2.0) : 213663458
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::CISCOCONFIGMANMIB
	Wed May 25 08:09:02 2016: cache: 1.3.6.1.4.1.9.9.43.1.1.3.0
	Wed May 25 08:09:02 2016: i know package Monitoring::GLPlugin::SNMP::MibsAndOids::CISCOCONFIGMANMIB
	Wed May 25 08:09:02 2016: GET: CISCO-CONFIG-MAN-MIB::ccmHistoryStartupLastChanged (1.3.6.1.4.1.9.9.43.1.1.3.0) : 213579935
	Wed May 25 08:09:02 2016: $self->{components}->{config_subsystem} = Classes::Cisco::IOS::Component::ConfigSubsystem->new()
	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::IOS::check_config_subsystem

	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::IOS::Component::ConfigSubsystem::check_messages

	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::IOS::Component::ConfigSubsystem::set_thresholds

	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::IOS::Component::ConfigSubsystem::check_thresholds

	[CONFIG]
	ccmHistoryRunningLastChanged: 1421205421.24 (Wed Jan 14 04:17:01 2015)
	ccmHistoryRunningLastSaved: 1421205466.58 (Wed Jan 14 04:17:46 2015)
	ccmHistoryStartupLastChanged: 1421204631.35 (Wed Jan 14 04:03:51 2015)
	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::IOS::check_messages

	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::IOS::check_messages

	Wed May 25 08:09:02 2016: AUTOLOAD Classes::Cisco::IOS::nagios_exit

	CRITICAL - running config is ahead of startup config since 715852 minutes. changes will be lost in case of a reboot
	checking config
	running config is ahead of startup config since 715852 minutes. changes will be lost in case of a reboot

So with the higher margin this check shouldn't alert anymore because the difference between the retrieved timeticks is less than the margin - but it does. Any idea?

**Comment by mhoogveld** [comment]
Looking into this a but further I noticed that the check also uses the devices' uptime.
The margin is only used, as the name indicates, for the time after a reload.

The logic is like this:
If running-changed < starup-changed then:
...If running-changed falls within 5 mins after reload then:
......config consided not changed
...else:
......config consided changed

This invalidated my previous remarks about "changes made up to 5 min after a config save, will not be detected". They _will_ actually be detected, unless right after a reload.

Maybe something like this will help give insight
`print("run-unchanged : ", $runningUnchangedDuration, "\n");`
`print("run-margin    : ", $runningChangedMarginAfterReload, "\n");`
`print("uptime        : ", $self->uptime(), "\n");`

**Comment by Napsty** [comment]
I've reprogrammed this a little bit for my own purpose. Here I don't use the current timestamp at all, the calculations happen only with the values retrieved by SNMP.

	  # If running config has been changed after the startup config
	  if ($runningUnchangedDuration > ($startupUnchangedDuration + $runningChangedMarginAfterReload)) {
	    # This means that the current running config is newer than the last startup save, even by adding the margin.
	    # So config changes were done but not saved within the margin time
	    my $diff = $runningUnchangedDuration - $startupUnchangedDuration;
	    my $errorlevel = 2;
	    $self->add_warning(sprintf "running config is %d minutes (= %d hours = %d days) ahead of startup config. changes will be lost in case of a reboot",
	      $diff / 60, $diff / 60 / 60, $diff / 60 / 60 /24);
	  }
	  else {
	    # Running config is the same or within the margin of the Startup save
	    $self->add_ok("saved config is up to date");
	  }

This gives the following output if the running config's timestamp is newer than the "startup config save"-timestamp AND the added margin (in my case fixed to 86400):

	# /usr/lib/nagios/plugins/check_nwc_health-test --hostname 1.2.3.4 --community public --mode check-config  -v -v -v
	I am a Cisco IOS Software, C3750 Software (C3750-IPSERVICESK9-M), Version 12.2(44)SE, RELEASE SOFTWARE (fc1)
	Copyright (c) 1986-2008 by Cisco Systems, Inc.
	Compiled Sat 05-Jan-08 00:29 by weiliu
	[CONFIG]
	ccmHistoryRunningLastChanged: 1460706670.4 (Fri Apr 15 09:51:10 2016)
	ccmHistoryRunningLastSaved: 1420516252.49 (Tue Jan  6 04:50:52 2015)
	ccmHistoryStartupLastChanged: 1420516246.44 (Tue Jan  6 04:50:46 2015)
	WARNING - running config is ahead of startup config since 669840 minutes (= 11164 hours = 465 days). changes will be lost in case of a reboot
	checking config

I know this is not a real replacement for the current code (hence no pull request) but maybe it gives an idea whether or not to ditch the current timestamp in the calculation?

**Comment by Napsty** [comment]
I suspect a (old) bug in IOS. Many switches (more than 10) show wrong date information in SNMP while in IOS the configs were saved. Time sync is correct. As long as the firmwares (still from 2008) are not updated, I have no choice but to disable the check-config check in our monitoring. What a bummer. I'm therefore closing the ticket as I assume that with the check everything is ok.
