### ISSUE TITLE
 nortel/avaya memory usage is higher than default warning

### ISSUE THREAD

**Issue by trentasis** [lausser/check_nwc_health#98]
Please change 80% to 85%, always show a warning with a 82% usage with medium usage

pull request:
https://github.com/lausser/check_nwc_health/pull/97

Thanks

**Comment by lausser** [comment]
Sorry, i have paying customers who willl absolutely not like it if i modify 
default thresholds.

How many devices did you test? What are the exact models and what are the 
memory usages?

Gerhard



Von: trentasis [mailto:notifications@github.com]
Gesendet: Dienstag, 12. Juli 2016 20:01
An: lausser/check_nwc_health
Betreff: [lausser/check_nwc_health] nortel/avaya memory usage is higher than 
default warning (#98)



Please change 80% to 85%, always show a warning with a 82% usage with medium 
usage

pull request:
#97 <https://github.com/lausser/check_nwc_health/pull/97>

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/98> , or mute the thread 
<https://github.com/notifications/unsubscribe/AAMJOL-NDxQ-D1f8FBA5GY--S8HNKGIVks5qU9ZSgaJpZM4JKqEu> 
. 
<https://github.com/notifications/beacon/AAMJOBCLs4apbu9Uc2pgM8SB327djN-Sks5qU9ZSgaJpZM4JKqEu.gif>

**Comment by trentasis** [comment]
tried with 3 model 4548 with latest firmware versions, it seems that latest firmware versions are requiring more memory.
if change this vakue for only nortel switchs i not correct, I think that a good option could be to have an optio warning and critical as parameter option and not a hardcoded parameter in code... or are there other options?


thanks

**Comment by trentasis** [comment]
Any new about this issue, It will be great that warning and critical can be defined as global parameters, to allow to change this values depending what are the needs...

**Comment by oakwhiz** [comment]
I have been using the additional arguments `--warning 90 --critical 95` to mitigate this issue.

**Comment by trentasis** [comment]
Hi,

Ok, perfect.
From what version is available this option?
Thanks


Missatge de oakwhiz <notifications@github.com> del dia dc., 6 de març 2019
a les 22:44:

**Comment by trentasis** [comment]
Thanks oakwhiz, tested with latest versions and with --warning 90 --critical 95 works great!
Good Job!
